// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dyVYvCZvgewVO2_3fEPAD1OrYQAu5aQ',
    appId: '1:865663574155:web:f381f858402de4e0f4b48e',
    messagingSenderId: '865663574155',
    projectId: 'heartsteal-19d36',
    authDomain: 'heartsteal-19d36.firebaseapp.com',
    storageBucket: 'heartsteal-19d36.firebasestorage.app',
    measurementId: 'G-3BQSJRRYZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpWpohqPHSBv8VkIZ575Dr7mybg5w3QlA',
    appId: '1:865663574155:android:e20a7902b94ff34cf4b48e',
    messagingSenderId: '865663574155',
    projectId: 'heartsteal-19d36',
    storageBucket: 'heartsteal-19d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQCfEbMaxZ5mbMUw1pacyTzn1h-RrXvWs',
    appId: '1:865663574155:ios:0e0f576bc007f6acf4b48e',
    messagingSenderId: '865663574155',
    projectId: 'heartsteal-19d36',
    storageBucket: 'heartsteal-19d36.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQCfEbMaxZ5mbMUw1pacyTzn1h-RrXvWs',
    appId: '1:865663574155:ios:0e0f576bc007f6acf4b48e',
    messagingSenderId: '865663574155',
    projectId: 'heartsteal-19d36',
    storageBucket: 'heartsteal-19d36.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8dyVYvCZvgewVO2_3fEPAD1OrYQAu5aQ',
    appId: '1:865663574155:web:65eddbeebd16a5f6f4b48e',
    messagingSenderId: '865663574155',
    projectId: 'heartsteal-19d36',
    authDomain: 'heartsteal-19d36.firebaseapp.com',
    storageBucket: 'heartsteal-19d36.firebasestorage.app',
    measurementId: 'G-7TZG3H5P5L',
  );
}
